### ISSUE TITLE
NPE when no username passed to list-projects

### ISSUE THREAD

**Issue by justinsb** [platformlayer/platformlayer#7]
~/bin/ks list-projects

Error running command: list-projects
java.lang.NullPointerException
       at org.platformlayer.keystone.cli.commands.ListProjects.runCommand(ListProjects.java:24)
       at com.fathomdb.cli.CliSimpleRepl.executeCommand(CliSimpleRepl.java:157)
       at com.fathomdb.cli.CliSimpleRepl.runCommand(CliSimpleRepl.java:91)
       at com.fathomdb.cli.CliBase.mainWithReturnCode(CliBase.java:168)
       at com.fathomdb.cli.CliBase.main(CliBase.java:47)
       at org.platformlayer.keystone.cli.KeystoneCli.main(KeystoneCli.java:42)

**Comment by justinsb** [comment]
Fixed; now issues an appropriate error message

(It wasn't parsing the arguments if there were none passed, which was a problem if an argument was required)
